/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Utility;

import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author rat
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
        setLayout(new FlowLayout(FlowLayout.CENTER,8,3));
    }
    
    public void initEvent(TableActionEvent event, int row){
        TableDelete.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
                event.onDelete(row);
            }
        });
        TableEdit.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
                event.onEdit(row);
            }
        });
        TableView.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
                event.onView(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TableDelete = new Utility.ActionButton();
        TableEdit = new Utility.ActionButton();
        TableView = new Utility.ActionButton();

        TableDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/output-onlinepngtools.png"))); // NOI18N
        TableDelete.setPreferredSize(new java.awt.Dimension(35, 35));
        TableDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TableDeleteActionPerformed(evt);
            }
        });

        TableEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/output-onlinepngtools (2).png"))); // NOI18N
        TableEdit.setMaximumSize(new java.awt.Dimension(35, 35));
        TableEdit.setMinimumSize(new java.awt.Dimension(35, 35));
        TableEdit.setPreferredSize(new java.awt.Dimension(35, 35));

        TableView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/output-onlinepngtools (1).png"))); // NOI18N
        TableView.setMaximumSize(new java.awt.Dimension(35, 35));
        TableView.setMinimumSize(new java.awt.Dimension(35, 35));
        TableView.setPreferredSize(new java.awt.Dimension(35, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(TableDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(TableEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TableView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TableDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(TableEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TableView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionButton2ActionPerformed

    private void TableDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TableDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TableDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Utility.ActionButton TableDelete;
    private Utility.ActionButton TableEdit;
    private Utility.ActionButton TableView;
    // End of variables declaration//GEN-END:variables
}
